name: Deploy static site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deployment bundle
        run: |
          mkdir -p dist
          cp index.html dist/index.html
          cp style.css dist/style.css
          cp script.js dist/script.js
          mkdir -p dist/config
          cp config/firebaseConfig.js dist/config/firebaseConfig.js
          cp *.png dist/ 2>/dev/null || true

      - name: Inject Firebase credentials
        run: |
          sed -i "s/data-firebase-api-key=\"\"/data-firebase-api-key=\"${FIREBASE_API_KEY}\"/" dist/index.html
          sed -i "s/data-firebase-auth-domain=\"\"/data-firebase-auth-domain=\"${FIREBASE_AUTH_DOMAIN}\"/" dist/index.html
          sed -i "s/data-firebase-project-id=\"\"/data-firebase-project-id=\"${FIREBASE_PROJECT_ID}\"/" dist/index.html
          sed -i "s/data-firebase-storage-bucket=\"\"/data-firebase-storage-bucket=\"${FIREBASE_STORAGE_BUCKET}\"/" dist/index.html
          sed -i "s/data-firebase-messaging-sender-id=\"\"/data-firebase-messaging-sender-id=\"${FIREBASE_MESSAGING_SENDER_ID}\"/" dist/index.html
          sed -i "s/data-firebase-app-id=\"\"/data-firebase-app-id=\"${FIREBASE_APP_ID}\"/" dist/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-site
          path: dist

      # Substitua esta etapa pelo provedor real de deploy (Firebase Hosting, S3, etc.)
      - name: Deployment placeholder
        run: echo "Add deployment command for your hosting provider here."
